### ISSUE TITLE
[Problem] Navbar-center が広げた時，適切な位置にこない

### ISSUE THREAD

**Issue by shuent** [shuent/trepi-v01#4]
CSSを調整し，解決しようとしたが，menuが広がった時ずれてしまう．

https://github.com/shuent/trepi-v01/blob/a6a517040b75a5e4b83417dd10bb625a3721bb0a/src/App.vue#L68-L70

![image](https://user-images.githubusercontent.com/12546161/31581064-e1c3a31c-b19b-11e7-8176-876e9376a311.png)

![image](https://user-images.githubusercontent.com/12546161/31581058-d2ca5ae0-b19b-11e7-8169-c31469f7c03d.png)

**Comment by shuent** [comment]
```css
.navbar .navbar-center {
  margin: auto;

}
@media (min-width:960px) {
  .navbar .navbar-center{
    margin: 0 calc(50% - 120px);
  }
}
```
無理やり調整したけど，もっといい方法がありそう．
